insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (1, 'topcare hemorrhoidal cooling', 2, 78, 52, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (2, 'ILLUMINATING PROTECTIVE PRIMER', 149, 68, 77, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (3, 'PediaCare Childrens Fever Reducer Pain Reliever Grape', 96, 52, 97, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (4, 'Healthy Accents Mucus Relief', 127, 78, 12, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (5, 'Paroxetine', 178, 64, 55, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (6, 'Bupivacaine Hydrochloride and Epinephrine', 45, 73, 53, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (7, 'Vaccines Detox', 44, 75, 47, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (8, 'Calendula', 19, 17, 45, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (9, 'PATADAY', 125, 60, 15, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (10, 'Tagamet', 79, 56, 56, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (11, 'Clemastine Fumarate', 157, 2, 33, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (12, 'health mart lice killing', 82, 50, 85, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (13, 'Cold Multi-Symptom', 9, 69, 8, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (14, 'Venlafaxine Hydrochloride', 154, 15, 100, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (15, 'Lien Cichorium', 138, 64, 23, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (16, 'Olive Oil Antibacterial Foaming Hand Wash', 34, 8, 16, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (17, 'Diethylpropion HCl Immediate-Release', 14, 1, 9, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (18, 'Extra Strength Headache Relief', 96, 13, 14, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (19, 'PANTOPRAZOLE SODIUM', 123, 69, 66, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (20, 'Cold Spot', 84, 21, 58, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (21, 'ULTRA CORRECTION LIFT', 76, 86, 3, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (22, 'Fludeoxyglucose F-18', 64, 50, 77, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (23, 'Next Choice', 75, 38, 51, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (24, 'COMTREX', 137, 5, 11, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (25, 'Burrobrush', 22, 50, 97, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (26, 'Lorazepam', 29, 29, 6, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (27, 'Acaifusion Lip Balm Broad Spectrum SPF 30', 200, 3, 39, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (28, 'Glyburide', 92, 92, 73, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (29, 'Phentermine Hydrochloride', 149, 53, 98, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (30, 'DDF Benzoyl Peroxide', 87, 16, 35, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (31, 'Dipyridamole', 116, 52, 65, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (32, 'Finasteride', 118, 25, 72, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (33, '4 in 1 Pressed Mineral SPF 15 Light Tan', 18, 64, 17, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (34, 'REGLAN', 180, 28, 39, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (35, 'Icy Hot Naturals', 189, 35, 17, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (36, 'Nitrogen', 172, 68, 80, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (37, 'Nesacaine', 67, 19, 80, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (38, 'Aplicare Povidone-iodine Scrub', 82, 85, 92, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (39, 'Adult Low Strength Aspirin', 137, 64, 19, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (40, 'PureFe Plus', 136, 73, 23, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (41, 'Complete Flu Care 4 Kids', 108, 93, 12, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (42, 'Levothyroxine Sodium', 167, 84, 82, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (43, 'Biofreeze', 84, 3, 79, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (44, 'Thompson Seedless Grape', 79, 5, 33, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (45, 'Triamcinolone Acetonide', 79, 49, 33, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (46, 'LBEL COULEUR LUXE AMPLIFIER XP', 184, 20, 99, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (47, 'HYVEE', 67, 55, 44, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (48, 'Pioglitazone', 32, 43, 25, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (49, 'GABITRIL', 137, 49, 93, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (50, 'Gonal-f RFF Redi-ject', 51, 97, 81, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (51, 'Benicar', 100, 21, 35, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (52, 'Scrub-In Surgical Scrub Brush/Sponge', 164, 6, 68, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (53, 'Atenolol', 190, 10, 42, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (54, 'Glyburide', 90, 37, 77, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (55, 'NU-DERM STARTER SET NORMAL-OILY', 83, 32, 31, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (56, 'Duloxetine', 151, 83, 86, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (57, 'Diclofenac Sodium', 97, 79, 38, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (58, 'Fluocinolone Acetonide', 86, 17, 44, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (59, 'CS-Brain', 8, 55, 59, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (60, 'NEUROSPORA INTERMEDIA', 163, 76, 83, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (61, 'Cucumber Melon Antibacterial Foaming Hand Wash', 175, 78, 91, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (62, 'Aveeno Positively Ageless Face', 30, 67, 6, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (63, 'Covergirl Outlast Stay Fabulous 3in1 Foundation', 167, 73, 22, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (64, 'Levetiracetam', 197, 38, 87, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (65, 'Carisoprodol', 46, 40, 78, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (66, 'Cefepime', 5, 40, 66, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (67, 'Sulindac', 141, 86, 65, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (68, 'Lamotrigine', 71, 16, 53, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (69, 'Bisacodyl', 98, 4, 84, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (70, 'Proactiv', 174, 66, 24, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (71, 'Famotidine - Acid Controller', 111, 90, 30, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (72, 'Bermuda Grass Smut', 73, 9, 13, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (73, 'Head and Shoulders 2in1', 70, 74, 61, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (74, 'Witch Hazel', 143, 23, 6, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (75, 'Rite Aid Sensitive Toothpaste Extra Whitening', 157, 31, 14, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (76, 'Ciprofloxacin', 32, 27, 32, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (77, 'Levetiracetam', 37, 49, 26, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (78, 'Metoprolol Tartrate', 197, 80, 39, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (79, 'Epirubicin Hydrochloride', 111, 11, 98, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (80, 'Nafcillin', 165, 71, 13, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (81, 'moisturizing anti-bacterial hand soap', 126, 100, 83, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (82, 'SP', 97, 14, 94, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (83, 'Viscum Pini', 196, 98, 40, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (84, 'Enulose', 20, 25, 99, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (85, 'Amlodipine Besylate and Benazepril Hydrochloride', 61, 53, 82, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (86, 'Isopropyl Alcohol', 30, 56, 59, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (87, 'POLYMYXIN B SULFATE and TRIMETHOPRIM SULFATE', 105, 1, 33, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (88, 'Neupro', 148, 14, 26, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (89, 'Fever Infection', 18, 6, 49, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (90, 'AHAVA ACTIVE DEADSEA MINERALS', 200, 44, 23, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (91, 'Pleo San Salm', 199, 2, 52, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (92, 'Chlorpromazine Hydrochloride', 149, 58, 31, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (93, 'Dental plus Whitening', 198, 89, 68, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (94, 'Energize', 125, 24, 27, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (95, 'Hydrocodone Bitartrate and Acetaminophen', 128, 80, 54, 2);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (96, 'Warfarin Sodium', 23, 36, 15, 3);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (97, 'Terbutaline Sulfate', 58, 39, 99, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (98, 'Phenytoin Sodium', 14, 59, 48, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (99, 'Glyburide', 97, 87, 36, 1);
insert into produto (cod_produto, nome_produto, valor_unitario, estoque, fk_clinica_cod_clinica, fk_tipo_produto_cod_tipo_produto) values (100, 'EMLA', 163, 71, 18, 1);
