insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (1, 'Delmor', '526224956-6', 'Annamark', 'Al Madān', 35);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (2, 'Bryce', '755403820-6', 'Summerview', 'Clichy', 82);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (3, 'Otis', '556869387-0', 'Pearson', 'Chunmuying', 18);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (4, 'Benny', '125560770-X', 'Northridge', 'Pantukan', 30);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (5, 'Wenonah', '386094798-2', 'Eagan', 'Wuyang', 40);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (6, 'Joaquin', '413618563-4', 'Lyons', 'Páchni', 2);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (7, 'Felicdad', '240514590-1', 'Hayes', 'Niquelândia', 1);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (8, 'Amory', '743418721-2', 'Swallow', 'Passo Fundo', 20);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (9, 'Oriana', '625507837-X', 'Vidon', 'Kol’chugino', 35);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (10, 'Charmine', '956364792-0', 'Wayridge', 'Tamuning-Tumon-Harmon Village', 89);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (11, 'Obidiah', '126936314-X', 'La Follette', 'Inayauan', 7);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (12, 'Hyacinthia', '142208336-5', 'Anthes', 'Port Hawkesbury', 37);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (13, 'Nickie', '245787185-9', 'Jenifer', 'Pangkalan Kasai', 26);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (14, 'Aarika', '660830808-6', 'Northridge', 'Sa Pá', 58);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (15, 'Pedro', '581431175-4', 'Elka', 'Chernelytsya', 59);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (16, 'Shepperd', '140265753-6', 'South', 'Wan’an', 75);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (17, 'Anton', '823685137-0', 'Anniversary', 'Fangzheng', 19);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (18, 'Vernen', '619415181-1', 'Leroy', 'Szczawnica', 83);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (19, 'Filmer', '365211150-8', 'Melrose', 'Khairpur', 79);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (20, 'Jerrilee', '280868103-8', 'Briar Crest', 'Novovarshavka', 1);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (21, 'Noellyn', '983811210-0', 'Ridgeway', 'Jihui', 27);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (22, 'Ginelle', '202149655-4', 'International', 'Neftekamsk', 77);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (23, 'Hanny', '451077326-9', 'Graceland', 'Condoroma', 72);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (24, 'Craggie', '779048625-X', 'Aberg', 'Iḩsim', 100);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (25, 'Keith', '532274398-7', 'Roxbury', 'Xuchang', 61);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (26, 'Rick', '703600384-7', 'Manley', 'Winterthur', 54);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (27, 'Zed', '282507297-4', 'Acker', 'Gorzkowice', 96);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (28, 'Melissa', '347190140-X', 'Red Cloud', 'Bugko', 28);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (29, 'Leonie', '207713518-2', 'Superior', 'Biscoitos', 100);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (30, 'Shelbi', '614591163-8', 'Cherokee', 'Santa Cruz', 49);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (31, 'Giff', '543958796-9', 'Monterey', 'Iqaluit', 97);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (32, 'Julie', '391227018-X', 'South', 'Zarzal', 2);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (33, 'Ethelbert', '046990515-8', 'Gale', 'Bente', 77);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (34, 'Ad', '720204845-0', 'Armistice', 'Kuroda', 29);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (35, 'Dusty', '322353423-7', 'Scofield', 'Tieling', 49);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (36, 'Hiram', '719648699-4', 'Lillian', 'Phu Khiao', 45);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (37, 'Heath', '425949483-X', 'Red Cloud', 'Guixi', 31);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (38, 'Spence', '963913660-3', 'Bashford', 'Weetobula', 44);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (39, 'Braden', '704621822-6', 'Springs', 'Nantes', 100);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (40, 'Kristine', '043381118-8', 'Pine View', 'Phonsavan', 30);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (41, 'Blithe', '557588686-7', 'Bluestem', 'Shengli', 53);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (42, 'Barri', '575519809-8', 'Scott', 'Sugihmukti', 43);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (43, 'Bartholomeus', '133871719-7', 'Summit', 'Mykolayiv', 31);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (44, 'Jefferey', '347530704-9', 'Rockefeller', 'Vällingby', 50);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (45, 'Moise', '909156657-4', 'Monterey', 'Rubizhne', 50);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (46, 'Sim', '853447660-8', 'Scofield', 'Huangcun', 58);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (47, 'Meriel', '715872614-2', 'Columbus', 'Ierápetra', 93);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (48, 'Aldin', '652718522-7', 'Monterey', 'Tangkilsari', 26);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (49, 'Aprilette', '242141512-8', 'Ohio', 'Épinal', 71);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (50, 'Willard', '411809031-7', 'Montana', 'Yuanshanzi', 28);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (51, 'Dody', '585904669-3', 'Village Green', 'Sumbe', 46);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (52, 'Angelika', '176308133-8', 'Kenwood', 'Jacaraú', 78);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (53, 'Jake', '033685305-X', 'Green Ridge', 'Huangfang', 77);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (54, 'Link', '887821260-1', 'Hintze', 'Vale de Rolas', 51);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (55, 'Erl', '343739362-6', 'Artisan', 'Kuroishi', 26);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (56, 'Halsy', '618124409-3', 'Warner', 'Shangfang', 64);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (57, 'Elihu', '656024557-8', 'Commercial', 'Qulsary', 49);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (58, 'Wolfy', '624580126-5', 'Mosinee', 'Chŏngju', 98);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (59, 'Gustavo', '414891706-6', 'Ronald Regan', 'Oli', 31);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (60, 'Darrin', '192873400-6', 'Homewood', 'Huangji', 75);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (61, 'Krysta', '029968857-7', 'Welch', 'Fanzhen', 18);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (62, 'Nickolas', '783618443-9', 'John Wall', 'Tamboril', 89);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (63, 'Ty', '114006767-2', 'Pearson', 'Mauá', 33);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (64, 'Sybila', '496664515-8', 'Namekagon', 'Briceni', 87);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (65, 'Reube', '052431195-1', 'Hazelcrest', 'Albert Town', 57);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (66, 'Katya', '173172181-1', 'Nova', 'Shimotoda', 6);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (67, 'Patrica', '447629194-5', 'Saint Paul', 'Taboão da Serra', 92);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (68, 'Hillier', '950175511-8', 'Summit', 'Laguna Salada', 60);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (69, 'Sauveur', '262399916-3', 'Butternut', 'Severnyy', 70);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (70, 'Rodolphe', '170814655-5', 'International', 'Jiulongshan', 43);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (71, 'Kial', '989590677-3', 'Scott', 'Jujur', 91);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (72, 'Blondie', '167929945-X', 'Merchant', 'Piippola', 61);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (73, 'Fax', '639734797-4', 'Goodland', 'Siborong-borong', 56);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (74, 'Rockie', '535464254-X', 'South', 'Fengshan', 93);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (75, 'Tracee', '626136100-2', 'Union', 'La Concepcion', 16);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (76, 'Noe', '564563302-4', 'Hagan', 'Asíni', 94);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (77, 'Iosep', '004051008-5', 'Sullivan', 'Korolev', 29);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (78, 'Timmi', '575586136-6', 'Valley Edge', 'Xiguantun Muguzu Manzuxiang', 28);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (79, 'Leann', '555100674-3', 'Stoughton', 'Chitral', 2);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (80, 'Laure', '788535016-9', 'Redwing', 'Maghār', 38);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (81, 'Jeremy', '054216557-0', 'Ronald Regan', 'Quxi', 85);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (82, 'Tiertza', '024139200-4', 'Gerald', 'Outeiro', 17);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (83, 'Harrietta', '309250273-6', 'Corben', 'Kalunan', 75);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (84, 'Ketti', '764748494-X', 'Sachtjen', 'Bani', 82);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (85, 'Neron', '914448023-7', 'Crest Line', 'Cavaillon', 88);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (86, 'Regine', '409684259-1', 'Badeau', 'Cipanggung', 61);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (87, 'Darin', '567364433-7', 'Sachtjen', 'Bilajari', 37);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (88, 'Jerri', '886978852-0', 'Hagan', 'Shazhouba', 75);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (89, 'Stinky', '217685560-4', 'Wayridge', 'Quesada', 62);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (90, 'Robert', '323831985-X', 'Grayhawk', 'Lucban', 91);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (91, 'Adolphe', '484216254-6', 'Donald', 'Tourcoing', 61);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (92, 'Conrad', '431811064-8', 'Carioca', 'Qulaybīyah', 76);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (93, 'Holmes', '231019607-X', 'Pennsylvania', 'Tqibuli', 11);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (94, 'Dorine', '787213896-4', 'Raven', 'Olhão', 55);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (95, 'Dot', '249031338-X', 'Hanson', 'Tanshan', 7);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (96, 'Johnnie', '119432065-1', 'Kennedy', 'Gò Quao', 18);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (97, 'Kelby', '934856588-5', 'Brown', 'Portobelo', 2);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (98, 'Bobbe', '391406569-9', 'Melvin', 'Guadalupe', 8);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (99, 'Blake', '831396204-6', 'Lake View', 'Khāliş', 84);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (100, 'Hamlin', '667100407-2', 'Susan', 'Nancy', 89);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (101, 'Wash', '772760438-0', 'Norway Maple', 'Náchod', 43);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (102, 'Britney', '699588993-2', 'Daystar', 'Tarragona', 15);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (103, 'Mamie', '996085287-3', 'American Ash', 'Falun', 55);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (104, 'Guillema', '570472964-9', 'Columbus', 'Gasa', 33);
insert into cliente (cod_cliente, nome_cliente, cpf, rua, cidade, fk_clinica_cod_clinica) values (105, 'Waylan', '274562051-7', 'Eastwood', 'Chuncheon', 54);