insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (1, 'Crested barbet', 'Trachyphonus vaillantii', 87, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (2, 'Flycatcher, tyrant', 'Myiarchus tuberculifer', 87, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (3, 'Cockatoo, long-billed', 'Cacatua tenuirostris', 11, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (4, 'Snake (unidentified)', 'unavailable', 81, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (5, 'Penguin, galapagos', 'Spheniscus mendiculus', 24, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (6, 'Rabbit, eastern cottontail', 'Sylvilagus floridanus', 15, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (7, 'Bushpig', 'Potamochoerus porcus', 91, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (8, 'Rhea, greater', 'Rhea americana', 62, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (9, 'Cape wild cat', 'Felis libyca', 35, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (10, 'Spectacled caiman', 'Caiman crocodilus', 77, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (11, 'Black curlew', 'Haematopus ater', 62, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (12, 'Indian porcupine', 'Hystrix indica', 37, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (13, 'Marabou stork', 'Leptoptilos crumeniferus', 63, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (14, 'Red-tailed phascogale', 'Phascogale calura', 34, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (15, 'Northern fur seal', 'Callorhinus ursinus', 35, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (16, 'Hornbill, yellow-billed', 'Tockus flavirostris', 62, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (17, 'Seal, northern fur', 'Callorhinus ursinus', 85, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (18, 'Teal, hottentot', 'Anas punctata', 36, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (19, 'Pine squirrel', 'Tamiasciurus hudsonicus', 28, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (20, 'Flamingo, lesser', 'Phoeniconaias minor', 12, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (21, 'Shrike, crimson-breasted', 'Laniaurius atrococcineus', 27, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (22, 'Possum, western pygmy', 'Cercatetus concinnus', 58, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (23, 'Cockatoo, roseate', 'Eolophus roseicapillus', 50, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (24, 'White-necked stork', 'Ciconia episcopus', 38, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (25, 'Red-billed hornbill', 'Tockus erythrorhyncus', 6, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (26, 'Dragon, netted rock', 'Ctenophorus ornatus', 9, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (27, 'Wolf, timber', 'Canis lupus lycaon', 20, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (28, 'Black rhinoceros', 'Diceros bicornis', 9, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (29, 'Currasow (unidentified)', 'Crax sp.', 80, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (30, 'Sifaka, verreaux''s', 'Propithecus verreauxi', 70, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (31, 'Spotted hyena', 'Crocuta crocuta', 67, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (32, 'Sifaka, verreaux''s', 'Propithecus verreauxi', 8, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (33, 'Green-winged macaw', 'Ara chloroptera', 58, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (34, 'Marabou stork', 'Leptoptilos crumeniferus', 93, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (35, 'Cattle egret', 'Bubulcus ibis', 13, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (36, 'Meerkat, red', 'Cynictis penicillata', 19, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (37, 'Vulture, king', 'Sarcorhamphus papa', 5, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (38, 'Sugar glider', 'Petaurus breviceps', 53, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (39, 'Heron, striated', 'Butorides striatus', 82, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (40, 'Vulture, oriental white-backed', 'Gyps bengalensis', 83, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (41, 'Sandgrouse, yellow-throated', 'Pterocles gutturalis', 39, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (42, 'Stork, white-necked', 'Ciconia episcopus', 70, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (43, 'Four-striped grass mouse', 'Rhabdomys pumilio', 89, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (44, 'Tortoise, burmese brown mountain', 'Manouria emys', 40, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (45, 'Spurfowl, yellow-necked', 'Francolinus leucoscepus', 80, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (46, 'Dabchick', 'Tachybaptus ruficollis', 57, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (47, 'Raven, cape', 'Corvus albicollis', 42, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (48, 'Roadrunner, greater', 'Geococcyx californianus', 40, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (49, 'Stork, greater adjutant', 'Leptoptilus dubius', 42, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (50, 'Southern lapwing', 'Vanellus chilensis', 15, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (51, 'Gull, kelp', 'Larus dominicanus', 76, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (52, 'Crimson-breasted shrike', 'Laniaurius atrococcineus', 24, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (53, 'Squirrel, african bush', 'Paraxerus cepapi', 49, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (54, 'Sally lightfoot crab', 'Graspus graspus', 37, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (55, 'Blue-tongued lizard', 'Tiliqua scincoides', 21, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (56, 'Nuthatch, red-breasted', 'Sitta canadensis', 32, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (57, 'Jackal, golden', 'Canis aureus', 19, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (58, 'Flying fox (unidentified)', 'unavailable', 35, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (59, 'Tarantula, salmon pink bird eater', 'Lasiodora parahybana', 41, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (60, 'Waxbill, violet-eared', 'Uraeginthus granatina', 64, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (61, 'Iguana, common green', 'Iguana iguana', 79, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (62, 'Indian tree pie', 'Dendrocitta vagabunda', 52, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (63, 'Arctic fox', 'Alopex lagopus', 4, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (64, 'African ground squirrel (unidentified)', 'Xerus sp.', 43, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (65, 'Rhesus macaque', 'Macaca mulatta', 52, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (66, 'Buffalo, american', 'Bison bison', 50, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (67, 'European red squirrel', 'Sciurus vulgaris', 48, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (68, 'Spotted hyena', 'Crocuta crocuta', 12, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (69, 'Common melba finch', 'Pytilia melba', 31, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (70, 'Dromedary camel', 'Camelus dromedarius', 69, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (71, 'Greater sage grouse', 'Centrocercus urophasianus', 17, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (72, 'Otter, north american river', 'Lutra canadensis', 99, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (73, 'Western palm tanager (unidentified)', 'unavailable', 65, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (74, 'Alligator, american', 'Alligator mississippiensis', 90, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (75, 'Glider, sugar', 'Petaurus breviceps', 89, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (76, 'Bear, polar', 'Ursus maritimus', 10, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (77, 'Slender loris', 'Loris tardigratus', 65, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (78, 'Snake, tiger', 'Notechis semmiannulatus', 76, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (79, 'Cat, native', 'Dasyurus viverrinus', 8, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (80, 'Gemsbok', 'Oryx gazella', 55, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (81, 'Antelope ground squirrel', 'Ammospermophilus nelsoni', 84, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (82, 'Purple grenadier', 'Uraeginthus granatina', 99, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (83, 'Stork, openbill', 'Anastomus oscitans', 44, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (84, 'Gray duiker', 'Sylvicapra grimma', 14, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (85, 'Skua, great', 'Catharacta skua', 18, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (86, 'Peccary, white-lipped', 'Tayassu pecari', 32, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (87, 'Dove, ring', 'Columba palumbus', 93, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (88, 'Squirrel, smith''s bush', 'Paraxerus cepapi', 53, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (89, 'Long-necked turtle', 'Chelodina longicollis', 57, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (90, 'Stork, woolly-necked', 'Ciconia episcopus', 54, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (91, 'Crested barbet', 'Trachyphonus vaillantii', 87, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (92, 'Baleen whale', 'Eubalaena australis', 6, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (93, 'Lorikeet, scaly-breasted', 'Trichoglossus chlorolepidotus', 39, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (94, 'White-throated robin', 'Irania gutteralis', 11, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (95, 'Arctic ground squirrel', 'Spermophilus parryii', 15, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (96, 'Steller sea lion', 'Eumetopias jubatus', 52, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (97, 'Ringtail cat', 'Bassariscus astutus', 23, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (98, 'Black-crowned night heron', 'Nycticorax nycticorax', 40, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (99, 'Heron, goliath', 'Ardea golieth', 36, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (100, 'Hawk-headed parrot', 'Deroptyus accipitrinus', 72, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (101, 'Boat-billed heron', 'Cochlearius cochlearius', 55, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (102, 'Buffalo, asian water', 'Bubalus arnee', 77, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (103, 'Red-headed woodpecker', 'Melanerpes erythrocephalus', 60, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (104, 'Boubou, southern', 'Laniarius ferrugineus', 92, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (105, 'African black crake', 'Limnocorax flavirostra', 12, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (106, 'Bear, black', 'Ursus americanus', 75, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (107, 'Oriental short-clawed otter', 'Aonyx cinerea', 28, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (108, 'Lapwing (unidentified)', 'Vanellus sp.', 23, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (109, 'Blue and gold macaw', 'Ara ararauna', 2, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (110, 'Flightless cormorant', 'Nannopterum harrisi', 28, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (111, 'Bird (unidentified)', 'unavailable', 70, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (112, 'Kafue flats lechwe', 'Kobus leche robertsi', 24, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (113, 'Vulture, oriental white-backed', 'Gyps bengalensis', 100, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (114, 'Vulture, griffon', 'Gyps fulvus', 27, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (115, 'Wallaby, river', 'Macropus agilis', 98, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (116, 'Southern right whale', 'Eubalaena australis', 92, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (117, 'Greater kudu', 'Tragelaphus strepsiceros', 64, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (118, 'Cormorant, neotropic', 'Phalacrocorax brasilianus', 49, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (119, 'Crimson-breasted shrike', 'Laniaurius atrococcineus', 54, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (120, 'Owl, snowy', 'Nyctea scandiaca', 47, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (121, 'Swainson''s francolin', 'Francolinus swainsonii', 21, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (122, 'European badger', 'Meles meles', 30, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (123, 'Beisa oryx', 'Oryx gazella', 3, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (124, 'Moccasin, water', 'Agkistrodon piscivorus', 18, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (125, 'Pallas''s fish eagle', 'Haliaeetus leucoryphus', 31, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (126, 'Dolphin, striped', 'Stenella coeruleoalba', 26, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (127, 'Water legaan', 'Varanus salvator', 63, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (128, 'Cat, african wild', 'Felis silvestris lybica', 32, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (129, 'Eurasian red squirrel', 'Sciurus vulgaris', 96, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (130, 'Black-capped chickadee', 'Parus atricapillus', 96, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (131, 'Capybara', 'Hydrochoerus hydrochaeris', 17, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (132, 'Square-lipped rhinoceros', 'Ceratotherium simum', 88, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (133, 'Baboon, gelada', 'Theropithecus gelada', 47, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (134, 'Goose, snow', 'Anser caerulescens', 46, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (135, 'Steenbuck', 'Raphicerus campestris', 43, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (136, 'Macaw, blue and gold', 'Ara ararauna', 10, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (137, 'Mexican boa', 'Boa constrictor mexicana', 15, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (138, 'Carpet python', 'Morelia spilotes variegata', 77, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (139, 'Cat, native', 'Dasyurus viverrinus', 26, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (140, 'Boat-billed heron', 'Cochlearius cochlearius', 45, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (141, 'Hudsonian godwit', 'Limosa haemastica', 95, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (142, 'Flicker, field', 'Colaptes campestroides', 88, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (143, 'Francolin, coqui', 'Francolinus coqui', 77, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (144, 'Tortoise, burmese black mountain', 'Manouria emys', 27, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (145, 'Water legaan', 'Varanus salvator', 52, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (146, 'Gray rhea', 'Rhea americana', 89, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (147, 'Hornbill, red-billed', 'Tockus erythrorhyncus', 82, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (148, 'White-winged tern', 'Chlidonias leucopterus', 75, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (149, 'Cat, jungle', 'Felis chaus', 44, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (150, 'Bandicoot, short-nosed', 'Isoodon obesulus', 76, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (151, 'Sloth, two-toed tree', 'Choloepus hoffmani', 62, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (152, 'Greater rhea', 'Rhea americana', 49, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (153, 'Red and blue macaw', 'Ara chloroptera', 46, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (154, 'Cockatoo, long-billed', 'Cacatua tenuirostris', 3, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (155, 'Peacock, blue', 'Pavo cristatus', 3, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (156, 'Squirrel, thirteen-lined', 'Spermophilus tridecemlineatus', 54, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (157, 'Crowned hawk-eagle', 'Spizaetus coronatus', 53, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (158, 'Hen, sage', 'Centrocercus urophasianus', 55, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (159, 'Hornbill, yellow-billed', 'Tockus flavirostris', 36, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (160, 'Western pygmy possum', 'Cercatetus concinnus', 42, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (161, 'Blue-breasted cordon bleu', 'Uraeginthus angolensis', 99, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (162, 'Civet cat', 'Bassariscus astutus', 99, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (163, 'Green heron', 'Butorides striatus', 77, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (164, 'Gecko, ring-tailed', 'Cyrtodactylus louisiadensis', 99, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (165, 'Southern lapwing', 'Vanellus chilensis', 58, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (166, 'Caracara, yellow-headed', 'Milvago chimachima', 44, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (167, 'Flicker, campo', 'Colaptes campestroides', 31, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (168, 'Malachite kingfisher', 'Corythornis cristata', 85, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (169, 'Crake, african black', 'Limnocorax flavirostra', 78, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (170, 'Red-billed toucan', 'Ramphastos tucanus', 84, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (171, 'Helmeted guinea fowl', 'Numida meleagris', 50, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (172, 'White-rumped vulture', 'Gyps bengalensis', 98, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (173, 'Snowy sheathbill', 'Chionis alba', 6, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (174, 'Rhinoceros, square-lipped', 'Ceratotherium simum', 8, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (175, 'Lily trotter', 'Actophilornis africanus', 70, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (176, 'Puma, south american', 'Felis concolor', 5, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (177, 'Owl, great horned', 'Bubo virginianus', 96, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (178, 'Flamingo, roseat', 'Phoenicopterus ruber', 72, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (179, 'Platypus', 'Ornithorhynchus anatinus', 59, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (180, 'Yellow-throated sandgrouse', 'Pterocles gutturalis', 91, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (181, 'Buffalo, asian water', 'Bubalus arnee', 8, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (182, 'Black-crowned crane', 'Balearica pavonina', 14, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (183, 'Lizard, goanna', 'Varanus sp.', 100, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (184, 'Fox, arctic', 'Alopex lagopus', 1, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (185, 'Galapagos albatross', 'Diomedea irrorata', 98, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (186, 'Brazilian tapir', 'Tapirus terrestris', 6, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (187, 'Meerkat, red', 'Cynictis penicillata', 75, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (188, 'Black-capped capuchin', 'Cebus apella', 91, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (189, 'Rat, white-faced tree', 'Echimys chrysurus', 82, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (190, 'Whale, killer', 'Orcinus orca', 52, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (191, 'Sparrow, rufous-collared', 'Zonotrichia capensis', 23, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (192, 'Yellow-headed caracara', 'Milvago chimachima', 15, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (193, 'Brown hyena', 'Hyaena brunnea', 72, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (194, 'Cormorant, king', 'Phalacrocorax albiventer', 95, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (195, 'Finch, common melba', 'Pytilia melba', 81, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (196, 'Waxbill, black-cheeked', 'Estrilda erythronotos', 10, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (197, 'Downy woodpecker', 'Picoides pubescens', 25, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (198, 'Swan, trumpeter', 'Cygnus buccinator', 5, 1);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (199, 'Bee-eater, carmine', 'Merops nubicus', 66, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (200, 'Spectacled caiman', 'Caiman crocodilus', 9, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (201, 'Swamp deer', 'Cervus duvauceli', 61, null);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (202, 'Little grebe', 'Tachybaptus ruficollis', 94, null);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (203, 'Catfish, blue', 'Ictalurus furcatus', 91, null);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (204, 'Sage grouse', 'Centrocercus urophasianus', 73, null);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (205, 'Western grey kangaroo', 'Macropus fuliginosus', 93, null);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (206, 'Knob-nosed goose', null, 88, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (207, 'Macaw, scarlet', null, 99, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (208, 'Frogmouth, tawny', null, 100, 3);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (209, 'Long-billed cockatoo', null, 97, 2);
insert into animal (cod_animal, nome_animal, especie, fk_Cliente_cod_cliente, fk_porte_animal_cod_portanimal) values (210, 'Tortoise, galapagos', null, 70, 1);
